name: map_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^4.0.0
  flutter_map_location_marker: ^6.0.0
  flutter_map_marker_popup: ^5.1.0
  flutter_svg: ^2.0.7
  latlong2: any
  supabase_flutter: ^1.10.3

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/Faster_One/FasterOne-Regular.ttf
    - assets/Globe.svg
    - assets/People.svg
    - assets/Chat.svg
    - assets/FilterButton.svg
    - assets/Search.svg
    - assets/Settings.svg
  fonts:
    - family: FasterOne
      fonts:
        - asset: assets/fonts/Faster_One/FasterOne-Regular.ttf
